# SPDX-License-Identifier: LGPL-2.0-or-later
# RPM spec for kde-windows-system-tray
# Builds the Plasma 6 system tray applet (org.kde.windowsmodern.systemtray)
# and its translations (zh_CN, zh_TW, ja, de, ko, fr).

Name:           kde-windows-system-tray
Version:        45.0.0
Release:        2%{?dist}
Summary:        Windows 11–style System Tray plasmoid for KDE Plasma 6

License:        LGPL-2.0-or-later
URL:            https://github.com/RaceConditionWinner/Kde-windows-system-tray
Source0:        https://github.com/evernightvista/Kde-windows-system-tray/archive/refs/heads/main.zip

# ---- Build-time dependencies ------------------------------------------------
BuildRequires:  gcc-c++
BuildRequires:  cmake
BuildRequires:  extra-cmake-modules

# Qt6
BuildRequires:  qt6-qtbase-devel
BuildRequires:  qt6-qtdeclarative-devel

# KDE Frameworks 6
BuildRequires:  kf6-kpackage-devel
BuildRequires:  kf6-kconfig-devel
BuildRequires:  kf6-ki18n-devel
BuildRequires:  kf6-kcoreaddons-devel
BuildRequires:  kf6-kwindowsystem-devel
BuildRequires:  kf6-kio-devel
BuildRequires:  kf6-kiconthemes-devel
BuildRequires:  kf6-kitemmodels-devel
BuildRequires:  kf6-kservice-devel
BuildRequires:  kf6-kxmlgui-devel
BuildRequires:  kf6-kjobwidgets-devel
BuildRequires:  kf6-kcmutils-devel

# Plasma
BuildRequires:  libplasma-devel
BuildRequires:  plasma-workspace-devel

Requires:       plasma-workspace >= 6.7.91

%description
A Windows 11–style System Tray applet for KDE Plasma 6, forked from
KDE's plasma-workspace systemtray. Provides the Windows Modern tray
layout with a system cluster (Network/Volume/Battery), quick settings
flyout, and background app management.

Translations included: Simplified Chinese, Traditional Chinese, Japanese,
German, Korean, and French.

%prep
%autosetup -n Kde-windows-system-tray-main

%build
%cmake -DCMAKE_BUILD_TYPE=Release \
       -DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
       system-tray
%cmake_build

%install
%cmake_install

# Discover and own the compiled .mo translation catalogs.
# %find_lang searches %{_localedir}/*/LC_MESSAGES/<name>.mo and writes
# the resulting file list to %{name}.lang, which is included in
# the file list below via %%files -f.
%find_lang plasma_applet_org.kde.windowsmodern.systemtray

%files -f plasma_applet_org.kde.windowsmodern.systemtray.lang
%license LICENSE
%doc README.md
# This is a C++ Plasma Containment, not a pure-QML plasmoid package.
# plasma_add_applet() compiles the C++ plugin, the QML sources
# (ecm_target_qml_sources) and the metadata.json into a single .so via
# Qt resources. Therefore the only runtime artifact is the applet plugin
# below — there is no KPackage directory under share/plasma/plasmoids/
# and no kxmlgui5 .rc file installed. Listing those (non-existent) paths
# here was what caused the "File not found" RPM build errors.
%{_qt6_plugindir}/plasma/applets/org.kde.windowsmodern.systemtray.so
# The .mo catalogs are owned via the -f file list generated by %find_lang
# above; do not list locale files manually to avoid duplicate ownership.

%changelog
* Sat Oct 10 2026 KairikiFedora <13278297951@sina.cn> - 45.0.0-2
- Add Back animations

* Fri Oct 09 2026 KairikiFedora <13278297951@sina.cn> - 45.0.0-1
- Initial RPM package
- Windows 11–style System Tray plasmoid for KDE Plasma 6
- Includes translations for zh_CN, zh_TW, ja, de, ko, fr
- Uses find_lang for locale file ownership
